channels:
 - hcc
 - bioconda
dependencies:
 - pyvcf
 - tabix
 - pytabix
 - snakemake
 - pysam
 - neo4j-python-driver
 - fastcluster
 - numpy
 - pandas
 - lftp 
 - sqlite
 - xlrd
 - openpyxl
 - scikit-learn
 - intervaltree
