channels:
 - hcc
 - bioconda
dependencies:
 - pyvcf
 - tabix
 - pytabix
 - pysam
 - numpy
 - pandas
 - sqlite
 - scikit-learn
 - intervaltree

 - snakemake
 - matplotlib
 - lftp
 - xlrd
 - openpyxl
 - fastcluster 
